apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "py-block3.fullname" . }}-deployment
  labels:
    app: py-block3
    {{- include "py-block3.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: py-block3
  template:
    metadata:
      labels:
        app: py-block3
        {{- include "py-block3.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe}}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.externalRefs.configMapName }}
                  key: APP_ENV
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.externalRefs.configMapName }}
                  key: APP_VERSION
            - name: STARTUP_DELAY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.externalRefs.configMapName }}
                  key: STARTUP_DELAY
            - name: APP_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalRefs.secretName }}
                  key: APP_SECRET_TOKEN
