apiVersion: v1
kind: Service
metadata:
  name: {{ include "py-block3.fullname" . }}-service
  labels:
    app: py-block3
    {{- include "py-block3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: py-block3
